<title>Week 3 &mdash; SpEn</title>
    <?php $this->layout = 'ccsdt'; ?>
    <meta http-equiv="refresh" content="240"><div id="title">
    <h2 id="sdc"><center>CCSDT for DCSS v0.32</center></h2>
    <h2>Week 3 &mdash; SpEn</h2></div><div id="content"><div id="times"><span class="label">Week of 2024-11-15</span></div><div id="combo"><span class="label">Character: </span>Spriggan Enchanter</div>
<div id="bonus"><span class="label">Bonus 1: </span>Collect a rune before entering Shoals, Snake, Spider, or Swamp.<br/>
<span class="label">Bonus 2: </span>Collect at least 5 runes before entering the Depths.</div>
<div id="gods"><span class="label">Gods: </span>Ashenzari, Dithmenos, Lugonu</div><div class="card"><table><tr class="head">
    <th>Player</th>
    <th>Unique Kill</th>
    <th>Branch Enter</th>
    <th>Branch End</th>
    <th>Champion God</th>
    <th>Collect a Rune</th>
    <th>Collect 3 Runes</th>
    <th>Obtain the Orb</th>
    <th>Win</th>
    <th>Bonus 1</th>
    <th>Bonus 2</th>
    <th>Total</th>
    </tr><tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/GeeHouse/morgue-GeeHouse-20241117-013043.txt">GeeHouse</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//DocSulfur/morgue-DocSulfur-20241120-234902.txt">DocSulfur</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/tengutamer/morgue-tengutamer-20241120-081828.txt">tengutamer</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Sapher/morgue-Sapher-20241115-155925.txt">Sapher</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/RepoMan/morgue-RepoMan-20241118-153917.txt">RepoMan</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/Blyxx/morgue-Blyxx-20241120-105113.txt">Blyxx</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//TheMeInTeam/morgue-TheMeInTeam-20241120-213952.txt">TheMeInTeam</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/Neopolis/morgue-Neopolis-20241120-171752.txt">Neopolis</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Flugkiller/morgue-Flugkiller-20241115-152855.txt">Flugkiller</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/JavaGenius/morgue-JavaGenius-20241117-143008.txt">JavaGenius</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/tizzy/morgue-tizzy-20241116-035640.txt">tizzy</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="https://archive.nemelex.cards/morgue//Coo1/morgue-Coo1-20241120-150939.txt">Coo1</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/grothendieck/morgue-grothendieck-20241119-174316.txt">grothendieck</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/TCC/morgue-TCC-20241118-233221.txt">TCC</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/piedemon/morgue-piedemon-20241116-023930.txt">PieDemon</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//EugeneJudo/morgue-EugeneJudo-20241121-003817.txt">EugeneJudo</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Midpoint/morgue-Midpoint-20241121-194403.txt">Midpoint</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">6</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/MirrMurr/morgue-MirrMurr-20241118-211657.txt">MirrMurr</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//browni3141/morgue-browni3141-20241119-132018.txt">browni3141</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//particleface/morgue-particleface-20241117-163213.txt">particleface</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/jt/morgue-jt-20241115-214024.txt">jt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/kickassninja/morgue-kickassninja-20241121-061253.txt">kickassninja</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Moanerette/morgue-Moanerette-20241117-223139.txt">Moanerette</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/nojaa/morgue-nojaa-20241120-224631.txt">nojaa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//TheBenjamin/morgue-TheBenjamin-20241121-134536.txt">TheBenjamin</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/Broken26/morgue-Broken26-20241116-034156.txt">Broken26</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/EvilAshe/morgue-EvilAshe-20241118-152005.txt">EvilAshe</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Dibbuk/morgue-Dibbuk-20241116-005257.txt">Dibbuk</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//RoGGa/morgue-RoGGa-20241115-202325.txt">RoGGa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Dwargi/morgue-Dwargi-20241121-205419.txt">Dwargi</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="alive"><td class="name">0xDEADFACE</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Pedant/morgue-Pedant-20241116-161102.txt">Pedant</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//agentchuck/morgue-agentchuck-20241116-174748.txt">agentchuck</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Fougere/morgue-Fougere-20241120-161926.txt">Fougere</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://archive.nemelex.cards/morgue//ww7/morgue-ww7-20241117-122843.txt">ww7</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/smoky173/morgue-smoky173-20241115-115700.txt">smoky173</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//grumposus/morgue-grumposus-20241115-033943.txt">grumposus</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Daunt/morgue-Daunt-20241116-190401.txt">Daunt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//planckenstein/morgue-planckenstein-20241115-030115.txt">planckenstein</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/chlorine/morgue-chlorine-20241119-201456.txt">chlorine</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/dannycarnage/morgue-dannycarnage-20241117-184842.txt">dannycarnage</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Jame/morgue-Jame-20241120-003439.txt">Jame</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//JolietJake/morgue-JolietJake-20241116-065805.txt">JolietJake</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="alive"><td class="name">Datul</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//vittis/morgue-vittis-20241116-184434.txt">vittis</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Nonny/morgue-Nonny-20241115-013205.txt">Nonny</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/flestrin/morgue-flestrin-20241115-173014.txt">flestrin</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Arcadio/morgue-Arcadio-20241115-161242.txt">Arcadio</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/baljet/morgue-baljet-20241115-141003.txt">baljet</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//Scinternace/morgue-Scinternace-20241116-005024.txt">Scinternace</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/ozjimbob/morgue-ozjimbob-20241117-081053.txt">ozjimbob</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/xczxc/morgue-xczxc-20241116-055958.txt">xczxc</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/dragonlass/morgue-dragonlass-20241117-014451.txt">dragonlass</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Colgate/morgue-Colgate-20241115-152125.txt">Colgate</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Patrick2011b/morgue-Patrick2011b-20241115-005253.txt">Patrick2011b</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/cfcfcfcfcf/morgue-cfcfcfcfcf-20241115-164951.txt">cfcfcfcfcf</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//magipi/morgue-magipi-20241120-185003.txt">magipi</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Bombadil44/morgue-Bombadil44-20241115-224500.txt">Bombadil44</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Hans/morgue-Hans-20241116-184357.txt">Hans</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/HourglassMan/morgue-HourglassMan-20241116-173903.txt">HourglassMan</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/GnollFielding/morgue-GnollFielding-20241116-145822.txt">GnollFielding</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//SFR/morgue-SFR-20241120-140936.txt">SFR</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/lontrex/morgue-lontrex-20241118-134520.txt">lontrex</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/mrfahrenheit7/morgue-mrfahrenheit7-20241117-050932.txt">mrfahrenheit7</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/churchkey/morgue-churchkey-20241118-184114.txt">churchkey</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Zigmound/morgue-Zigmound-20241116-130336.txt">Zigmound</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Jannitor/morgue-Jannitor-20241117-155248.txt">Jannitor</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Dumalacath/morgue-Dumalacath-20241115-172305.txt">Dumalacath</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//community/morgue-community-20241115-031936.txt">community</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/cnlflgl/morgue-cnlflgl-20241119-144418.txt">cnlflgl</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/brinewave/morgue-brinewave-20241117-091432.txt">brinewave</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/PigKeeper/morgue-PigKeeper-20241119-213247.txt">PigKeeper</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/goupaloupa/morgue-goupaloupa-20241121-124137.txt">goupaloupa</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//tempest/morgue-tempest-20241117-072705.txt">tempest</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Migumi/morgue-Migumi-20241115-175556.txt">Migumi</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/TomBombadil/morgue-TomBombadil-20241121-124022.txt">TomBombadil</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Abbadon/morgue-Abbadon-20241116-063116.txt">Abbadon</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/ereinion/morgue-ereinion-20241120-111513.txt">ereinion</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//19mitch99/morgue-19mitch99-20241115-185041.txt">19mitch99</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Naiya55/morgue-Naiya55-20241115-011902.txt">Naiya55</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="alive"><td class="name">quokkamancerX</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="none"><td class="name">Axelsxxd</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">rypofalem</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">happinesssam</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Salticid</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">petercordia2</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">petercordia3</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Melancholic</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">FermentedSoyBoy</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Grugh</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Gnox</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Strat</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">prawnwizard</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">anonymouscript</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">snackwell</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">MysticSailboat</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">bayes525</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">shadowrider38</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">mauveavengr</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">0hmetheus</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">xho</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">shoop</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ventricule</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">1Anon</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">pedritolo</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">TeamPepega</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">againstme</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">person50605</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">wholewheatrotini</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">abclol0070</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Huckle</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">eadaral</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cpf86</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Pinetree</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">qwertydvorak</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ASCIIPhilia</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Draconianmaid</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">tlatlagkaus</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cheesecat</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">hyoungjinc</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">XobehCity</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">SpDrain</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">EngineV8</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Lovepenguin</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Rutnb</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">strontium90w</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">senlim</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">DispaterIsMyDaddy</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">yakattack</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Taxman1966</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">enarc13</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Ozzieoiler</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">thisguise</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Ubbricas</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Caterwaul</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ElricMelnibone</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">mcursa</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">MattyPfft</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">queenofdiamonds</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Taxman66</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">MalcolmRoseTourny</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">angelslayer</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cnedc</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">9to</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">UltimateCarl</td>
                <td colspan="10"></td><td class="total">0</td></tr></table></div></div>
   <div id="bottomtext">
     <span class="menu">CCSDT #1 for v0.32</a> : </span>
     <span class="menu"><a href="index.html">Overview</a> - </span>
     <span class="menu"><a href="rules.html">Details</a> - </span>
     <span class="menu"><a href="standings.html">Standings</a></span>
     <span class="menuspacer"></span>
     <span class="menu"><a href="1.html">Week 1</a> - </span>
     <span class="menu"><a href="2.html">Week 2</a> - </span>
     <span class="menu"><a href="3.html">Week 3</a> - </span>
     <span class="menu"><a href="4.html">Week 4</a> - </span>
     <span class="menu"><a href="5.html">Week 5</a></span>
   </div>
