<title>Week 5 &mdash; DsAl</title>
    <?php $this->layout = 'ccsdt'; ?>
    <meta http-equiv="refresh" content="240"><div id="title">
    <h2 id="sdc"><center>CCSDT for DCSS v0.32</center></h2>
    <h2>Week 5 &mdash; DsAl</h2></div><div id="content"><div id="times"><span class="label">Week of 2024-11-29</span></div><div id="combo"><span class="label">Character: </span>Demonspawn Alchemist</div>
<div id="bonus"><span class="label">Bonus 1: </span>Enter a rune branch with all base skills < 11.<br/>
<span class="label">Bonus 2: </span>Collect a rune in less than 15,000 turns.</div>
<div id="gods"><span class="label">Gods: </span>Jiyva, Nemelex Xobeh, Makhleb</div><div class="card"><table><tr class="head">
    <th>Player</th>
    <th>Unique Kill</th>
    <th>Branch Enter</th>
    <th>Branch End</th>
    <th>Champion God</th>
    <th>Collect a Rune</th>
    <th>Collect 3 Runes</th>
    <th>Obtain the Orb</th>
    <th>Win</th>
    <th>Bonus 1</th>
    <th>Bonus 2</th>
    <th>Total</th>
    </tr><tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Sapher/morgue-Sapher-20241130-091547.txt">Sapher</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Flugkiller/morgue-Flugkiller-20241129-211434.txt">Flugkiller</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="http://underhound.eu/crawl/morgue/RepoMan/morgue-RepoMan-20241202-212003.txt">RepoMan</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//Blyxx/morgue-Blyxx-20241204-101946.txt">Blyxx</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">10</td></tr>
<tr class="won"><td class="name"><a href="https://archive.nemelex.cards/morgue//Coo1/morgue-Coo1-20241201-130948.txt">Coo1</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//agentchuck/morgue-agentchuck-20241204-042022.txt">agentchuck</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//grumposus/morgue-grumposus-20241129-215558.txt">grumposus</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/Neopolis/morgue-Neopolis-20241205-152323.txt">Neopolis</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//Daunt/morgue-Daunt-20241205-231821.txt">Daunt</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="https://cbro.berotato.org/morgue//Pedant/morgue-Pedant-20241205-014804.txt">Pedant</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="total">9</td></tr>
<tr class="won"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Moanerette/morgue-Moanerette-20241201-170431.txt">Moanerette</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="total">8</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//EugeneJudo/morgue-EugeneJudo-20241204-214606.txt">EugeneJudo</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Dwargi/morgue-Dwargi-20241130-011042.txt">Dwargi</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Patrick2011b/morgue-Patrick2011b-20241205-213715.txt">Patrick2011b</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//RoGGa/morgue-RoGGa-20241129-215200.txt">RoGGa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">7</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Arcadio/morgue-Arcadio-20241201-143106.txt">Arcadio</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Fougere/morgue-Fougere-20241203-131354.txt">Fougere</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/JavaGenius/morgue-JavaGenius-20241130-083620.txt">JavaGenius</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//JolietJake/morgue-JolietJake-20241202-215417.txt">JolietJake</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">5</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/piedemon/morgue-piedemon-20241130-004241.txt">PieDemon</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//TheMeInTeam/morgue-TheMeInTeam-20241202-221110.txt">TheMeInTeam</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Dumalacath/morgue-Dumalacath-20241129-214428.txt">Dumalacath</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/lontrex/morgue-lontrex-20241205-031019.txt">lontrex</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/grothendieck/morgue-grothendieck-20241202-080617.txt">grothendieck</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/dragonlass/morgue-dragonlass-20241204-214720.txt">dragonlass</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Nonny/morgue-Nonny-20241130-001355.txt">Nonny</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/happinesssam/morgue-happinesssam-20241204-130758.txt">happinesssam</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">4</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/EvilAshe/morgue-EvilAshe-20241203-004717.txt">EvilAshe</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Zigmound/morgue-Zigmound-20241130-202405.txt">Zigmound</a></td><td class="pt">0</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/tizzy/morgue-tizzy-20241130-164048.txt">tizzy</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Colgate/morgue-Colgate-20241129-191036.txt">Colgate</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Dibbuk/morgue-Dibbuk-20241130-224753.txt">Dibbuk</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">1</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/MirrMurr/morgue-MirrMurr-20241201-160943.txt">MirrMurr</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/nojaa/morgue-nojaa-20241130-225116.txt">nojaa</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">3</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//vittis/morgue-vittis-20241204-174301.txt">vittis</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//TheBenjamin/morgue-TheBenjamin-20241129-172452.txt">TheBenjamin</a></td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="alive"><td class="name">tengutamer</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="alive"><td class="name">chlorine</td><td class="pt">1</td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">2</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/goupaloupa/morgue-goupaloupa-20241205-203633.txt">goupaloupa</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//magipi/morgue-magipi-20241129-135609.txt">magipi</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/ozjimbob/morgue-ozjimbob-20241203-010052.txt">ozjimbob</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/brinewave/morgue-brinewave-20241205-080358.txt">brinewave</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Jannitor/morgue-Jannitor-20241204-201925.txt">Jannitor</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/HourglassMan/morgue-HourglassMan-20241203-185049.txt">HourglassMan</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Jame/morgue-Jame-20241203-063420.txt">Jame</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//browni3141/morgue-browni3141-20241203-042516.txt">browni3141</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/baljet/morgue-baljet-20241201-095040.txt">baljet</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/TCC/morgue-TCC-20241129-183111.txt">TCC</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/ereinion/morgue-ereinion-20241129-103307.txt">ereinion</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/GeeHouse/morgue-GeeHouse-20241129-234629.txt">GeeHouse</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//tempest/morgue-tempest-20241204-181350.txt">tempest</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Naiya55/morgue-Naiya55-20241129-022144.txt">Naiya55</a></td><td class="pt">1</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">1</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//community/morgue-community-20241129-010040.txt">community</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/TomBombadil/morgue-TomBombadil-20241129-150743.txt">TomBombadil</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//Midpoint/morgue-Midpoint-20241129-204957.txt">Midpoint</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/Hans/morgue-Hans-20241129-131447.txt">Hans</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Bombadil44/morgue-Bombadil44-20241129-205606.txt">Bombadil44</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/xczxc/morgue-xczxc-20241203-053837.txt">xczxc</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://underhound.eu/crawl/morgue/Migumi/morgue-Migumi-20241129-200433.txt">Migumi</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/queenofdiamonds/morgue-queenofdiamonds-20241202-081844.txt">queenofdiamonds</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.akrasiac.org/rawdata/mrfahrenheit7/morgue-mrfahrenheit7-20241130-095038.txt">mrfahrenheit7</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//planckenstein/morgue-planckenstein-20241129-020859.txt">planckenstein</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://cbro.berotato.org/morgue//19mitch99/morgue-19mitch99-20241129-211939.txt">19mitch99</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//cfcfcfcfcf/morgue-cfcfcfcfcf-20241129-213136.txt">cfcfcfcfcf</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.dcss.io/crawl/morgue//Scinternace/morgue-Scinternace-20241130-013626.txt">Scinternace</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="http://crawl.xtahua.com/crawl/morgue/jt/morgue-jt-20241129-214744.txt">jt</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="dead"><td class="name"><a href="https://crawl.project357.org/morgue/Abbadon/morgue-Abbadon-20241130-111545.txt">Abbadon</a></td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="pt">0</td><td class="total">0</td></tr>
<tr class="none"><td class="name">Axelsxxd</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">rypofalem</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Salticid</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">petercordia2</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">petercordia3</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Melancholic</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">FermentedSoyBoy</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Grugh</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">GnollFielding</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Gnox</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Strat</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">prawnwizard</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">anonymouscript</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">snackwell</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">particleface</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">MysticSailboat</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">bayes525</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">shadowrider38</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Datul</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">mauveavengr</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">0hmetheus</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">SFR</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">quokkamancerX</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">xho</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">shoop</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">dannycarnage</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ventricule</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">PigKeeper</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">1Anon</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">DocSulfur</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">flestrin</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">pedritolo</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">smoky173</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">TeamPepega</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">againstme</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">person50605</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">wholewheatrotini</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">abclol0070</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Huckle</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">eadaral</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cpf86</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Pinetree</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">qwertydvorak</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ww7</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ASCIIPhilia</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Draconianmaid</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">tlatlagkaus</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cheesecat</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">hyoungjinc</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cnlflgl</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">XobehCity</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">SpDrain</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">EngineV8</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Lovepenguin</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Rutnb</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">strontium90w</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">senlim</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">DispaterIsMyDaddy</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">yakattack</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Taxman1966</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">kickassninja</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">enarc13</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Ozzieoiler</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">thisguise</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Ubbricas</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Caterwaul</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">ElricMelnibone</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">mcursa</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">MattyPfft</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Taxman66</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">MalcolmRoseTourny</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">churchkey</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">0xDEADFACE</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">angelslayer</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">cnedc</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">Broken26</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">9to</td>
                <td colspan="10"></td><td class="total">0</td></tr><tr class="none"><td class="name">UltimateCarl</td>
                <td colspan="10"></td><td class="total">0</td></tr></table></div></div>
   <div id="bottomtext">
     <span class="menu">CCSDT #1 for v0.32</a> : </span>
     <span class="menu"><a href="index.html">Overview</a> - </span>
     <span class="menu"><a href="rules.html">Details</a> - </span>
     <span class="menu"><a href="standings.html">Standings</a></span>
     <span class="menuspacer"></span>
     <span class="menu"><a href="1.html">Week 1</a> - </span>
     <span class="menu"><a href="2.html">Week 2</a> - </span>
     <span class="menu"><a href="3.html">Week 3</a> - </span>
     <span class="menu"><a href="4.html">Week 4</a> - </span>
     <span class="menu"><a href="5.html">Week 5</a></span>
     <span id="updated"><span class="label">Last Update: </span>2024-12-06 00:00 UTC</span>
   </div>
